# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(20, 9, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.outputlabel.setFont(font)
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputlabel.setLineWidth(2)
        self.outputlabel.setMidLineWidth(1)
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel.setObjectName("outputlabel")
        self.percentbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("%"))
        self.percentbutton.setGeometry(QtCore.QRect(20, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentbutton.setFont(font)
        self.percentbutton.setObjectName("percentbutton")
        self.clearbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("C"))
        self.clearbutton.setGeometry(QtCore.QRect(100, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.clearbutton.setFont(font)
        self.clearbutton.setObjectName("clearbutton")
        self.arrowbutton = QtWidgets.QPushButton(self.centralwidget ,clicked=lambda: self.remove_it())
        self.arrowbutton.setGeometry(QtCore.QRect(180, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.arrowbutton.setFont(font)
        self.arrowbutton.setObjectName("arrowbutton")
        self.dividebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.dividebutton.setGeometry(QtCore.QRect(260, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dividebutton.setFont(font)
        self.dividebutton.setObjectName("dividebutton")
        self.sevenbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.sevenbutton.setGeometry(QtCore.QRect(20, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenbutton.setFont(font)
        self.sevenbutton.setObjectName("sevenbutton")
        self.eightbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.eightbutton.setGeometry(QtCore.QRect(100, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightbutton.setFont(font)
        self.eightbutton.setObjectName("eightbutton")
        self.ninebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.ninebutton.setGeometry(QtCore.QRect(180, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ninebutton.setFont(font)
        self.ninebutton.setObjectName("ninebutton")
        self.multiplybutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.multiplybutton.setGeometry(QtCore.QRect(260, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplybutton.setFont(font)
        self.multiplybutton.setObjectName("multiplybutton")
        self.fourbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.fourbutton.setGeometry(QtCore.QRect(20, 240, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourbutton.setFont(font)
        self.fourbutton.setObjectName("fourbutton")
        self.fivebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.fivebutton.setGeometry(QtCore.QRect(100, 240, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fivebutton.setFont(font)
        self.fivebutton.setObjectName("fivebutton")
        self.sixbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.sixbutton.setGeometry(QtCore.QRect(180, 240, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixbutton.setFont(font)
        self.sixbutton.setObjectName("sixbutton")
        self.minusbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.minusbutton.setGeometry(QtCore.QRect(260, 240, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusbutton.setFont(font)
        self.minusbutton.setObjectName("minusbutton")
        self.onebutton = QtWidgets.QPushButton(self.centralwidget , clicked=lambda: self.press_it("1"))
        self.onebutton.setGeometry(QtCore.QRect(20, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.onebutton.setFont(font)
        self.onebutton.setObjectName("onebutton")
        self.twobutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.twobutton.setGeometry(QtCore.QRect(100, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twobutton.setFont(font)
        self.twobutton.setObjectName("twobutton")
        self.threebutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.threebutton.setGeometry(QtCore.QRect(180, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threebutton.setFont(font)
        self.threebutton.setObjectName("threebutton")
        self.plusbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.plusbutton.setGeometry(QtCore.QRect(260, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusbutton.setFont(font)
        self.plusbutton.setObjectName("plusbutton")
        self.plusminusbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus_it())
        self.plusminusbutton.setGeometry(QtCore.QRect(20, 400, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminusbutton.setFont(font)
        self.plusminusbutton.setObjectName("plusminusbutton")
        self.zerobutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.zerobutton.setGeometry(QtCore.QRect(100, 400, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zerobutton.setFont(font)
        self.zerobutton.setObjectName("zerobutton")
        self.decimalbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.decimal_it())
        self.decimalbutton.setGeometry(QtCore.QRect(180, 400, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.decimalbutton.setFont(font)
        self.decimalbutton.setObjectName("decimalbutton")
        self.equalbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.math_it())
        self.equalbutton.setGeometry(QtCore.QRect(260, 400, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalbutton.setFont(font)
        self.equalbutton.setObjectName("equalbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def remove_it(self):
        screen = self.outputlabel.text()
        screen=screen[:-1]
        self.outputlabel.setText(screen)

    def math_it(self):
        screen = self.outputlabel.text()
        try:
            answer = eval(screen)
            self.outputlabel.setText(str(answer))
        except:
            self.outputlabel.setText("error")
        
        

    def plus_minus_it(self):
        screen = self.outputlabel.text()
        if "-" in screen:
            self.outputlabel.setText(screen.replace("-" , ""))
        else:
            self.outputlabel.setText(f'-{screen}')

    def decimal_it(self):
        screen = self.outputlabel.text()
        
        if screen[-1] == ".":
            pass
        else:
            self.outputlabel.setText(f'{screen}.')

    def press_it(self , pressed):
        if pressed == "C":
            self.outputlabel.setText("0")
        else:
            if self.outputlabel.text() == "0":
                self.outputlabel.setText("")
            self.outputlabel.setText(f'{self.outputlabel.text()}{pressed}')
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputlabel.setText(_translate("MainWindow", "0"))
        self.percentbutton.setText(_translate("MainWindow", "%"))
        self.clearbutton.setText(_translate("MainWindow", "C"))
        self.arrowbutton.setText(_translate("MainWindow", "<<"))
        self.dividebutton.setText(_translate("MainWindow", "/"))
        self.sevenbutton.setText(_translate("MainWindow", "7"))
        self.eightbutton.setText(_translate("MainWindow", "8"))
        self.ninebutton.setText(_translate("MainWindow", "9"))
        self.multiplybutton.setText(_translate("MainWindow", "x"))
        self.fourbutton.setText(_translate("MainWindow", "4"))
        self.fivebutton.setText(_translate("MainWindow", "5"))
        self.sixbutton.setText(_translate("MainWindow", "6"))
        self.minusbutton.setText(_translate("MainWindow", "-"))
        self.onebutton.setText(_translate("MainWindow", "1"))
        self.twobutton.setText(_translate("MainWindow", "2"))
        self.threebutton.setText(_translate("MainWindow", "3"))
        self.plusbutton.setText(_translate("MainWindow", "+"))
        self.plusminusbutton.setText(_translate("MainWindow", "+/-"))
        self.zerobutton.setText(_translate("MainWindow", "0"))
        self.decimalbutton.setText(_translate("MainWindow", "."))
        self.equalbutton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
